// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import {
    // ClerkProvider,
    // SignInButton,
    SignedIn,
    // SignedOut,
    // UserButton,
} from "@clerk/nextjs";
// import "./globals.css";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <ClerkProvider>
//             <html lang="en">
//                 <body
//                     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//                 >
//                     <SignedOut>
//                         <SignInButton />
//                     </SignedOut>
//                     <SignedIn>
//                         <UserButton />
//                         {children}
//                     </SignedIn>
//                 </body>
//             </html>
//         </ClerkProvider>
//     );
// }
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/Header";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                >
                    <Header /> {/* Include the header here */}
                    <SignedIn>
                        <main>{children}</main>{" "}
                    </SignedIn>
                    {/* Ensure children are displayed below the header */}
                </body>
            </html>
        </ClerkProvider>
    );
}
